server:
  port: 8095
  
security:
  oauth2:
    client:
      client-id: auth_id # client를 인증하기 위한 ID
      client-secret: auth_secret # client를 인증하기 위한 Password
    resource:
      jwt:
        key-value: jwt_secret_key # jwt를 암호화하기 위한 비밀키       
